apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: test-pending
  name: test-pending
spec:
  containers:
  - image: nginx:alpine
    name: test-pending
    resources: 
      requests:
        memory: 1Ti
      limits:
        memory: 1Ti
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
